sudo: required
services:
    - docker

before_install:
    - docker build -t noobdocker403/docker-react -f Dockerfile.dev .

script:
    - docker run noobdocker403/docker-react npm run test -- --coverage
