language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t noobdocker403/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true noobdocker403/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-039835854470"
    bucket_path: "docker"
    on:
        branch: master
    acess_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY